# Generated by Django 5.1.5 on 2025-02-13 00:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_userfollowwallet_user_alter_wallet_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinwallet',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 21, 31, 24, 257063)),
        ),
        migrations.CreateModel(
            name='SellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 2, 12, 21, 31, 24, 258064))),
                ('stock_in_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.stockinwallet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
