# Generated by Django 5.1.6 on 2025-02-19 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_stockinwallet_total_alter_buyhistory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('Brasileira', 'Brasileira'), ('Cripto', 'Cripto'), ('Internacional', 'Internacional')], default='Brasileira', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 20, 9, 41, 541161)),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 20, 9, 41, 541161)),
        ),
    ]
